ktor:
    development: true
    application:
        modules:
            - io.ktor.chat.LoggingKt.logging
            - io.ktor.chat.SecurityKt.security
            - io.ktor.chat.MailKt.mail
            - io.ktor.chat.RestKt.rest
            - io.ktor.chat.HealthCheckKt.healthCheck
            - io.ktor.chat.DatabasesKt.database
            - io.ktor.chat.RepositoriesKt.repositories
            - io.ktor.chat.AuthenticationKt.auth
            - io.ktor.chat.UsersKt.users
            - io.ktor.chat.MessagesKt.messages
            - io.ktor.chat.RoomsKt.rooms
            - io.ktor.chat.MembershipsKt.members
            - io.ktor.chat.SignalingKt.signaling
    deployment:
        port: 8080
        host: 0.0.0.0

jwt:
    audience: audience
    issuer: issuer
    realm: realm

security:
    secret: S3crE4_P@55w0Rd

database:
    main:
        url: "jdbc:postgresql://localhost:5432/myktorchat"
        user: luminousdragon
        driver: org.postgresql.Driver
        password: helloworld
    test:
        url: "jdbc:h2:file:../h2/db"
        user: root
        driver: org.h2.Driver
        password: ""
